//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace foodweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class team
    {
        public int tid { get; set; }
        public string t_name { get; set; }
        public string t_role { get; set; }
        public string t_img { get; set; }
    }
}
